[build-system]
requires = ["setuptools >= 61.2.0", "wheel >= 0.37", "build >= 0.7", "versioningit >= 1.1"]
build-backend = "setuptools.build_meta"

[tool.versioningit]
write.file = "python/sun_earth_geometry/_version.py"

[tool.versioningit.vcs]
method = "git"
match = ["v*"]
default-tag = "0.0.0"