name: Publish Docs
on:
  push:
    branches:
      - master
    paths:
      - docs
      - overrides
  workflow_dispatch:


jobs:
  whoami:
    uses: ./.github/workflows/event_user.yml

  deploy:
    needs: whoami
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git user.name and user.email
        run: |
          git config --global user.email ${{needs.whoami.outputs.email}}
          git config --global user.name ${{needs.whoami.outputs.username}}

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install tox>=3.25.0
        run: pip install "tox>=3.25.0"

      - name: Update CHANGELOG.md using towncrier
        run: tox -e changes

      - name: Push repository
        run: git push origin

      - name: Deploy to GH Pages
        run: tox -e deploy-docs
